services:
  streamlit:
    build: .
    container_name: streamlit-vqe-new
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.enableCORS=false
      --server.enableXsrfProtection=false
      --browser.gatherUsageStats=false
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
